### ISSUE TITLE
Crash when trying to view certain recurring events

### ISSUE THREAD

**Issue by e-t-l** [Etar-Group/Etar-Calendar#1384]
This happens for some, but not all, recurring events. I haven't narrowed down what the difference is. But when I try to view or edit the recurring event, Etar crashes with the following crash report:
```
type: crash
osVersion: google/panther/panther:13/TQ2A.230405.003.E1/2023042900:user/release-keys
package: ws.xsoh.etar:34
process: ws.xsoh.etar
processUptime: 1495 + 224 ms

com.android.calendarcommon2.EventRecurrence$InvalidFormatException: Invalid integer value: WE
FREQ=WEEK
	at com.android.calendarcommon2.EventRecurrence$PartParser.parseIntRange(EventRecurrence.java:689)
	at com.android.calendarcommon2.EventRecurrence$ParseByDay.parseWday(EventRecurrence.java:835)
	at com.android.calendarcommon2.EventRecurrence$ParseByDay.parsePart(EventRecurrence.java:818)
	at com.android.calendarcommon2.EventRecurrence.parse(EventRecurrence.java:627)
	at com.android.calendar.EventInfoFragment.updateEvent(EventInfoFragment.java:1550)
	at com.android.calendar.EventInfoFragment.-$$Nest$mupdateEvent(Unknown Source:0)
	at com.android.calendar.EventInfoFragment$QueryHandler.onQueryComplete(EventInfoFragment.java:2383)
	at com.android.calendar.AsyncQueryService.handleMessage(AsyncQueryService.java:357)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

**Comment by e-t-l** [comment]
It looks like Etar is improperly handling "weekday" recurrence values. In the above crash report, `Invalid integer value: WE` corresponds to me trying to view an event that recurs every week on Wednesday; I've seen similar crash reports when trying to view recurring weekly Monday and Saturday events, for example, which crash with error `Invalid integer value: MO` and `Invalid integer value: SA`, respectively. 

It is clear that Etar is expecting an integer value for recurring events with `FREQ=WEEK` (where Monday = `1`, Tuesday = `2`, ... Sunday = `7`), HOWEVER CalDAV/ics handles this with string values (where Monday = `MO`, Tuesday = `TU`, ... Sunday = `SU`). (I think the ICS format may actually except either the integer or string values. The issue is that Etar doesn't.)

Fixing this bug should be fairly straightforward: weekly string values just need to be converted to integers (so `MO` becomes `1`, `TU` becomes `2`, ... `SU` becomes `7`) so as not to throw an error.

This is where my usefulness starts to diminish. I'm not familiar enough with the organization of Etar's code to know where the best place to implement this fix is. @Gitsaibot @jspricke do you have any ideas where to go from here?
