### ISSUE TITLE
Etar crashes upon opening of recurring meeting

### ISSUE THREAD

**Issue by mgw2013** [Etar-Group/Etar-Calendar#1409]
A13 - Etar V 13(33) from AOSP/Lineageos and Etar1.0.34 from F-Droid. Cal sync via DAV X5. 

Reproducible on both Etar instances: Etar crashes upon trying to open an existing recurring meeting.

**Comment by jspricke** [comment]
Can you share the meeting definition (as a icalendar file) and an logcat of the crash?

**Comment by mgw2013** [comment]
Sorry - had to fiddle around with adb... here we go:
--------- beginning of crash
06-12 13:50:38.813  5934  5934 E AndroidRuntime: FATAL EXCEPTION: main
06-12 13:50:38.813  5934  5934 E AndroidRuntime: Process: org.lineageos.etar, PID: 5934
06-12 13:50:38.813  5934  5934 E AndroidRuntime: com.android.calendarcommon2.EventRecurrence$InvalidFormatException: Invalid integer value: 2TU
06-12 13:50:38.813  5934  5934 E AndroidRuntime: FREQ=MONTH
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence$PartParser.parseIntRange(EventRecurrence.java:689)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence$ParseByDay.parseWday(EventRecurrence.java:835)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence$ParseByDay.parsePart(EventRecurrence.java:810)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence.parse(EventRecurrence.java:627)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendar.EventInfoFragment.updateEvent(EventInfoFragment.java:1550)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendar.EventInfoFragment.-$$Nest$mupdateEvent(Unknown Source:0)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendar.EventInfoFragment$QueryHandler.onQueryComplete(EventInfoFragment.java:2383)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.calendar.AsyncQueryService.handleMessage(AsyncQueryService.java:357)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7896)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-12 13:50:38.813  5934  5934 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
06-12 13:50:38.817  1555  6014 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
06-12 13:50:38.914   525   525 I Zygote  : Process 5934 exited due to signal 9 (Killed)

**Comment by mgw2013** [comment]
BEGIN:VCALENDAR
PRODID:-//1&1 Mail & Media GmbH/WEB.DE Kalender Server
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
CREATED:20230127T101304Z
LAST-MODIFIED:20230612T110148Z
DTSTAMP:20230612T110148Z
UID:84f9c295-2875-4057-87b9-2ffca206762c
SUMMARY:Vorstandssitzung
ORGANIZER;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;SENT-BY="xxxxxxxxx"
ATTENDEE;CN=Michael;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mailto:xxxxxxxx
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
RRULE:FREQ=MONTHLY;UNTIL=20231231T140000Z;BYDAY=2TU
EXDATE;TZID=Europe/Berlin:20230411T150000
CATEGORIES:Besprechung
X-MOZ-LASTACK:20230214T182633Z
DTSTART;TZID=Europe/Berlin:20230214T150000
DTEND;TZID=Europe/Berlin:20230214T170000
TRANSP:OPAQUE
X-MOZ-SNOOZE-TIME-1676383200000000:20230214T183133Z
X-MOZ-GENERATION:128
SEQUENCE:1
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
LAST-MODIFIED:20201010T011803Z
TZURL:http://tzurl.org/zoneinfo/Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
X-PROLEPTIC-TZNAME:LMT
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

**Comment by Rpnpif** [comment]
Hello,
I had the same issue. Debugging with adb tell me that the culprit was Android Web Viewer 114.0.5735.196.
So others applications had the same issue.
I deinstalled it and returned back to the factory release 70 that fix this issue.

So try this to see if it fix it..

**Comment by mgw2013** [comment]
You are refering to Android System WebView I presume... no other app's share the issue (so different from your environment). With latest version of OS it got even worse - I can't even open the recurring event:
07-18 13:33:00.476 15899 15899 D AndroidRuntime: Shutting down VM
07-18 13:33:00.476 15899 15899 E AndroidRuntime: FATAL EXCEPTION: main
07-18 13:33:00.476 15899 15899 E AndroidRuntime: Process: org.lineageos.etar, PID: 15899
07-18 13:33:00.476 15899 15899 E AndroidRuntime: com.android.calendarcommon2.EventRecurrence$InvalidFormatException: Invalid integer value: 2TU
07-18 13:33:00.476 15899 15899 E AndroidRuntime: FREQ=MONTH
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence$PartParser.parseIntRange(EventRecurrence.java:689)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence$ParseByDay.parseWday(EventRecurrence.java:835)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence$ParseByDay.parsePart(EventRecurrence.java:810)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendarcommon2.EventRecurrence.parse(EventRecurrence.java:627)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendar.EventInfoFragment.updateEvent(EventInfoFragment.java:1550)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendar.EventInfoFragment.-$$Nest$mupdateEvent(Unknown Source:0)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendar.EventInfoFragment$QueryHandler.onQueryComplete(EventInfoFragment.java:2383)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.calendar.AsyncQueryService.handleMessage(AsyncQueryService.java:357)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7930)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-18 13:33:00.476 15899 15899 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

**Comment by jspricke** [comment]
I think the problem is a different calendar entry. I guess it contains something like this:
```
RRULE:BYDAY=2TU\nFREQ=MONTH
```
Whereas it should probably be:
```
RRULE:BYDAY=2TU;FREQ=MONTHLY
```

Not sure about the newline in there. Can you have an other look if any calendar entry looks like that?
You could also try copying the calendar provider SQLite DB off the device. Ping me if you need help with this.

Also not sure where this bug belongs, probably DavX5 should not add such an rrule into the calendar provider. Otherwise The Android parser, in android_frameworks_opt_calendar, Etar uses should be hardened to parse such strings.

**Comment by mgw2013** [comment]
Could be... the entry originates from Thunderbird calendar sync'd with GMX calendar and is replicated via DavX5 to the device.  Room for improvement regarding the "standard" I guess.

**Comment by Rpnpif** [comment]
@mgw2013 
> You are refering to Android System WebView I presume... no other app's share the issue (so different from your environment). With latest version of OS it got even worse - I can't even open the recurring event: 

Yes you are right. Sorry for the mismatch.
