### ISSUE TITLE
Crash when importing Klimastreik event in Germany

### ISSUE THREAD

**Issue by rugk** [Etar-Group/Etar-Calendar#1429]
## STR

Open/import the calendar file linked here: https://tickets.fridaysforfuture.de/fff/klimastreik23/
[fff-klimastreik23-0.ics.zip](https://github.com/Etar-Group/Etar-Calendar/files/12437638/fff-klimastreik23-0.ics.zip)

Direct link: https://tickets.fridaysforfuture.de/fff/klimastreik23/ical

## What happens
Crash/I do not even see Etar starting.

Logcat:
```
Not starting debugger since process cannot load the jdwp agent.
FATAL EXCEPTION: main
Process: org.calyxos.etar, PID: 17386
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.calyxos.etar/com.android.calendar.ImportActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
	at com.android.calendar.ImportActivity.getLocalTimeFromString(ImportActivity.java:52)
	at com.android.calendar.ImportActivity.parseCalFile(ImportActivity.java:189)
	at com.android.calendar.ImportActivity.onCreate(ImportActivity.java:44)
	at android.app.Activity.performCreate(Activity.java:8342)
	at android.app.Activity.performCreate(Activity.java:8321)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1421)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more
```

## What should happen
No crash.

## System

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.12.1.  
source: CalyxOS
version: v. 13
Build-ID: `TQ3A.230805.001.23412010`

Reported downstream as https://gitlab.com/CalyxOS/calyxos/-/issues/1800

**Comment by theimpulson** [comment]
Fixed in https://github.com/Etar-Group/Etar-Calendar/issues/1429
