### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Spiralo-Idioide** [Etar-Group/Etar-Calendar#1532]
# Infos

- Model: Unihertz Titan
- Version : Android 10
- App versions : 
  - f-droid : 1.0.36, 1.0.37, 1.036
  - play-store : 1.0.38

# Problem

- Installation of the app
- Launching the app
- Accept the calendar and file permissions
- The app crash 

If I don't accept calendar permission the app does not crash. But as soon as I accord it the app crash.

# Logs (I think)

```
onResume getComponentName().getClassName()：com.android.calendar.AllInOneActivity
Shutting down VM
FATAL EXCEPTION: main
Process: ws.xsoh.etar, PID: 29525
java.lang.RuntimeException: Unable to resume activity {ws.xsoh.etar/com.android.calendar.AllInOneActivity}: java.lang.SecurityException: Failed to find provider com.android.calendar for user 0; expected to find a valid ContentProvider for this authority
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4233)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4265)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: java.lang.SecurityException: Failed to find provider com.android.calendar for user 0; expected to find a valid ContentProvider for this authority
	at android.os.Parcel.createException(Parcel.java:2072)
	at android.os.Parcel.readException(Parcel.java:2040)
	at android.os.Parcel.readException(Parcel.java:1988)
	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1234)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2263)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2251)
	at com.android.calendar.AllInOneActivity.onResume(AllInOneActivity.java:617)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:7993)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4223)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4265) 
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041) 
	at android.os.Handler.dispatchMessage(Handler.java:107) 
	at android.os.Looper.loop(Looper.java:214) 
	at android.app.ActivityThread.main(ActivityThread.java:7386) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:344)
	at android.content.IContentService$Stub.onTransact(IContentService.java:482)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

**Comment by Spiralo-Idioide** [comment]
Thank you ! It worked perfectly.

Also thank for the fast answers.

**Comment by levone1** [comment]
> Thank you ! It worked perfectly.
> 
> Also thank for the fast answers.

Can you tell me what worked perfectly?  Did you install some other package to make it work?
