### ISSUE TITLE
Crash on show calenders item

### ISSUE THREAD

**Issue by MrDiba** [Etar-Group/Etar-Calendar#312]
Phone: Xiaomi Mi6
Android version: 7.1.1
Etar build version: 1.0.12

When I try to open a calender item Etar crashes shutting down the app.

My phone creates the following log:

java.lang.NullPointerException: Attempt to invoke interface method 'void android.accessibilityservice.IAccessibilityServiceClient.onInterrupt()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1690)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.interrupt(IAccessibilityManager.java:330)
	at android.view.accessibility.AccessibilityManager.interrupt(AccessibilityManager.java:451)
	at com.android.calendar.DayView.doSingleTapUp(DayView.java:3842)
	at com.android.calendar.DayView.access$4500(DayView.java:96)
	at com.android.calendar.DayView$CalendarGestureListener.onSingleTapUp(DayView.java:4928)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
	at com.android.calendar.DayView.onTouchEvent(DayView.java:4222)
	at android.view.View.dispatchTouchEvent(View.java:10036)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3195)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
	at android.view.View.dispatchPointerEvent(View.java:10258)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4524)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4389)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3929)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3982)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3948)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4075)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3956)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4132)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3929)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3982)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3948)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3956)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3929)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6339)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6313)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6274)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6445)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6276)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)

I will try to make a video showing the crash.

**Comment by jspricke** [comment]
Does Etar has the needed rights? Check in the app info.

**Comment by MrDiba** [comment]
I have checked the permissions and to me it looks that the app has all the rights:

![etar_permissions](https://user-images.githubusercontent.com/37332424/40051282-7d4d5194-583a-11e8-925e-f05d79d259d8.png)

Here is a GIF of the app crashing:

![etar_crash](https://user-images.githubusercontent.com/37332424/40051572-806147cc-583b-11e8-9664-162564930674.gif)

**Comment by MrDiba** [comment]
I did not think I did but turns out that my antivirus software uses the accessibility. Tuning off and on the permission to use the accessibility for the antivirus solved the problem, it is a miracle.

Thank you for the support, I will now close the issue.
