### ISSUE TITLE
Crash when accessing the settings screen

### ISSUE THREAD

**Issue by eduardosm** [Etar-Group/Etar-Calendar#651]
Accessing the settings from the hamburger menu will crash the application.

Logcat:
```
02-09 18:37:15.338  4721  4721 E AndroidRuntime: FATAL EXCEPTION: main
02-09 18:37:15.338  4721  4721 E AndroidRuntime: Process: ws.xsoh.etar, PID: 4721
02-09 18:37:15.338  4721  4721 E AndroidRuntime: java.lang.IllegalStateException: name must not be null
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at com.android.calendar.persistence.CalendarRepository$CalendarLiveData.getContentProviderValue(CalendarRepository.kt:73)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at com.android.calendar.persistence.CalendarRepository$CalendarLiveData.getContentProviderValue(CalendarRepository.kt:55)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at com.android.calendar.persistence.ContentProviderLiveData$getContentProviderValueAsync$1$accounts$1.invokeSuspend(ContentProviderLiveData.kt:60)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:891)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7470)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
02-09 18:37:15.338  4721  4721 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
02-09 18:37:15.342  1084  1620 W ActivityManager:   finishTopCrashedActivityLocked Force finishing activity ws.xsoh.etar/com.android.calendar.settings.SettingsActivity
02-09 18:37:15.345  1084  1620 W ActivityManager:   finishTopCrashedActivityLocked non_home Force finishing activity ws.xsoh.etar/com.android.calendar.AllInOneActivity
```

Device: Huawei Mate 10 with stock ROM (9.0.0.221)

**Comment by dschuermann** [comment]
This has been fixed in 1.0.21. Please update Etar.

Reference: https://github.com/Etar-Group/Etar-Calendar/issues/641
